//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;

namespace DatabaseConnector
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pattern
    {
    public Pattern() { }
    public Pattern(string name, BitArray bits ) {
      Name = name;
      Pattern1 = BitArrayToByteArray( bits );
    }
        public long Id { get; set; }
        public string Name { get; set; }
        public byte[] Pattern1 { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }

      private static byte[] BitArrayToByteArray( BitArray bits ) {
        byte[] ret = new byte[( bits.Length - 1 ) / 8 + 1];
        bits.CopyTo( ret, 0 );
        return ret;
      }
  }
}
